# Data Collector Service Configuration

server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug"  # debug, release, test
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Database configurations
database:
  mysql:
    host: "localhost"
    port: 3306
    username: "qtrade"
    password: "qtrade123"
    database: "qtrade"
    charset: "utf8mb4"
    parse_time: true
    loc: "Asia/Shanghai"
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 3600s
    
  mongodb:
    uri: "mongodb://qtrade:qtrade123@localhost:27017/qtrade"
    database: "qtrade"
    timeout: 10s
    
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    pool_size: 10
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    idle_timeout: 300s

# Logging configuration
log:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file
  file_path: "./logs/data-collector.log"
  max_size: 100  # MB
  max_backups: 5
  max_age: 30  # days
  compress: true

# Data collection configuration
collection:
  tushare:
    # 多Token配置支持
    tokens: [

    ]  # Tushare API tokens list, e.g. ["token1", "token2", "token3"]
    # 兼容单Token配置（优先级低于tokens）
    token: ""  # Single Tushare API token (fallback)
    base_url: "http://api.tushare.pro"
    timeout: 30s
    rate_limit: 200  # requests per minute
    retry_times: 3
    retry_interval: 1s
    # Token轮换配置
    token_rotation:
      enabled: true  # 是否启用token轮换
      strategy: "round_robin"  # 轮换策略：round_robin
      health_check_interval: 300s  # token健康检查间隔
    
  news:
    sources:
      - name: "财联社"
        url: "https://www.cls.cn"
        enabled: true
        interval: 600s  # 10 minutes
        
  policy:
    sources:
      - name: "央行"
        url: "http://www.pbc.gov.cn"
        enabled: true
        interval: 3600s  # 1 hour

# Scheduler configuration
scheduler:
  timezone: "Asia/Shanghai"
  jobs:
    stock_basic:
      cron: "0 0 18 * * 1-5"  # 工作日18:00
      enabled: true
      
    stock_quotes:
      cron: "*/5 9-15 * * 1-5"  # 工作日9:00-15:00，每5分钟
      enabled: true
      
    news_collection:
      cron: "*/10 * * * *"  # 每10分钟
      enabled: true
      
    policy_collection:
      cron: "0 * * * *"  # 每小时
      enabled: true